#!/usr/bin/env bash

# TODO: run init with selected device + replace default env in platformio.ini

#platformio init --ide clion --board nodemcu
platformio init --ide clion --board d1_mini_pro
platformio lib install DallasTemperature
platformio lib install 'WEMOS SHT3x'
